# No se puede hacer un ejecutable con dos main
sieteymedio: croupier.o player.o
	gcc croupier.o player.o -o sieteymedio

croupier.o: croupier.c
	gcc -c croupier.c

player.o: player.c
	gcc -c player.c
